### ISSUE TITLE
Rate and color bug 

### ISSUE THREAD

**Issue by anaismoller** [astrolabsoftware/fink-science-portal#279] opened 2022-02-07 04:05 UTC
Rate bugs when multiple observations are done in a single night for a filter
example:
https://fink-portal.org/ZTF21achkdwj
can be solved just using a groupie and doing a median probably on the values!

Delta color missing a value (probably a rounding issue)
for mjds 5921 and 5923

Thanks :)

**Comment by JulienPeloton** [comment] 2022-02-07 06:46
Good catch!

**Comment by JulienPeloton** [comment] 2022-02-16 13:00
Actually -- this is not a bug of the program. The fact that ZTF makes multiple observations of the same object within a night should not prevent us to report on each rate.

Now the question is how relevant those inter-night rates are? In a perfect world, they should not be different from inter-night rates -- the large scatter makes them looking big but in reality the error bar is also huge.

I could display the errorbar or make an option to trigger the grouping for visualisation purposes.

**Comment by anaismoller** [comment] 2022-02-17 03:26
1. A rate should only be given for the second observing date (how do you measure a rate of increase from the first observing point?)
2. we should have one rate point per night as it is rate/night. Else what do the other points mean? Thats why I guessed taking a median from a night as a value.

**Comment by JulienPeloton** [comment] 2022-02-17 14:41
We already take (1) into account -- first observing point has always a rate of 0. Regarding (2), there is probably a misunderstanding of what is available. 

Each object is made of alerts. Alerts can be emitted at any time (several alerts within the same night, and/or from different nights). We compute and expose the _rate between two subsequent measurements_, in units of mag/day (concretely `delta mag`/ `delta jd`) -- no matter the time difference between points. 

What you ask is different -- you would like to display the _rate between nights_, independently of the actual timeline of the object. Isn't it?

**Comment by anaismoller** [comment] 2022-02-21 06:56
Yes, it would make more physical sense to have a rate measurement per night instead of many. I understand this may go against the programatically way of seeing this ;)

**Comment by JulienPeloton** [comment] 2024-05-14 07:30
Fixed with the recent change by Sergey.

**Closed by JulienPeloton** 2024-05-14 07:30 UTC
Labels: supernovae
